[package]
name = "unfmt_macros"
version = "0.3.3"
edition = "2021"
rust-version = "1.81"
description = "A compile-time pattern matching library that reverses the interpolation process of `format!`."
license = "Apache-2.0"
authors = ["Mathematic Inc"]
repository = "https://github.com/mathematic-inc/unfmt"
categories = ["development-tools::procedural-macro-helpers", "parsing"]
keywords = ["format", "parsing", "pattern-matching", "proc-macro", "unformat"]

[lib]
path = "./unfmt_macros.rs"
proc-macro = true

[dependencies]
bstr = "1.13.1"
proc-macro2 = "1.0.107"
quote = "1.0.47"
syn = "3.0.4"

[lints]
workspace = true
