name: Publish

on:
  push:
    tags:
      - "*-v*"
      - "v*"

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@8459bc0c7e3759cdf591f513d9f141a95fef0a8f
      - name: Publish
        run: |
          if [[ $GITHUB_REF_NAME == *-v* ]]; then
            cargo publish --locked --token ${{ secrets.CRATES_IO_TOKEN }} -p ${GITHUB_REF_NAME%-v*}
          else
            cargo publish --locked --token ${{ secrets.CRATES_IO_TOKEN }}
          fi
