name: Publish

on:
  push:
    tags:
      - "*-v*"
      - "v*"

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b
      - name: Publish
        run: |
          if [[ $GITHUB_REF_NAME == *-v* ]]; then
            cargo publish --locked --token ${{ secrets.CRATES_IO_TOKEN }} -p ${GITHUB_REF_NAME%-v*}
          else
            cargo publish --locked --token ${{ secrets.CRATES_IO_TOKEN }}
          fi
