name: Publish

on:
  push:
    tags:
      - v*

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29
      - name: Publish
        run: |
          cargo publish --locked --token ${{ secrets.CRATES_IO_TOKEN }} -p unfmt_macros
          cargo publish --locked --token ${{ secrets.CRATES_IO_TOKEN }}
