name: Publish

on:
  push:
    tags:
      - v*

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
      - name: Publish
        run: |
          cargo publish --locked --token ${{ secrets.CRATES_IO_TOKEN }} -p unfmt_macros
          cargo publish --locked --token ${{ secrets.CRATES_IO_TOKEN }}
