name: Publish

on:
  push:
    tags:
      - v*

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@b17fe1e4d59a9d1d95a7aead5e6fcd13e50939a5
      - name: Publish
        run: |
          cargo publish --locked --token ${{ secrets.CRATES_IO_TOKEN }} -p unfmt_macros
          cargo publish --locked --token ${{ secrets.CRATES_IO_TOKEN }}
