name: Publish

on:
  push:
    tags:
      - "*-v*"

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@cd7d8d697e10461458bc61a30d094dc601a8b017
      - name: Publish
        run: cargo publish --locked --token ${{ secrets.CRATES_IO_TOKEN }} -p ${GITHUB_REF_NAME%-v*}
