name: Publish

on:
  push:
    tags:
      - v*

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b
      - name: Publish
        run: |
          cargo publish --locked --token ${{ secrets.CRATES_IO_TOKEN }} -p unfmt_macros
          cargo publish --locked --token ${{ secrets.CRATES_IO_TOKEN }}
