name: Publish

on:
  push:
    tags:
      - v*

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@b80ff79f1755d06ba70441c368a6fe801f5f3a62
      - name: Publish
        run: |
          cargo publish --locked --token ${{ secrets.CRATES_IO_TOKEN }} -p unfmt_macros
          cargo publish --locked --token ${{ secrets.CRATES_IO_TOKEN }}
