name: Release

on:
  push:
    branches: [main]

jobs:
  check-release:
    name: Check release
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
    steps:
      - name: Run release please
        id: release
        uses: google-github-actions/release-please-action@cc61a07e2da466bebbc19b3a7dd01d6aecb20d1e
        with:
          token: ${{ secrets.CHECK_RELEASE_TOKEN }}
          command: manifest
  release:
    needs: check-release
    name: Release
    runs-on: ubuntu-latest
    if: ${{ needs.check-release.outputs.release_created }}
    steps:
      - name: Check out repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      - name: Publish
        run: cargo publish --locked --token ${{ secrets.CARGO_REGISTRY_TOKEN }}
